# Generated by Django 2.2.5 on 2020-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191215_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity', max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='transport_charges',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Transport Charges if any', max_digits=12, verbose_name='Transport Charges'),
        ),
    ]
