# Generated by Django 2.2.5 on 2020-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200206_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='defected_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Defected Quantity Received', max_digits=12, verbose_name='Defected Items Quantity'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='invoice_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Invoice Quantity', max_digits=12, verbose_name='Invoice Quantity'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='received_quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity Received', max_digits=12, verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='transport_charges',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Transport Charges if any', max_digits=12, verbose_name='Transport Charges'),
        ),
    ]
