# Generated by Django 2.2.5 on 2021-01-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210105_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward',
            name='from_warehouse_name',
            field=models.ForeignKey(help_text='Warehouse from which part is being sent/outward', on_delete=django.db.models.deletion.PROTECT, related_name='outward_from_warehouse_name', to='inventory.Warehouse'),
        ),
    ]
