# Generated by Django 2.2.5 on 2021-01-09 15:07

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210105_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticinvoice',
            name='Invoice_parts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='parts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='invoice_date',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='invoice_number',
            field=models.CharField(max_length=40, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='transport_charges',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Transport Charges'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Vendor', verbose_name='Vendor Name'),
        ),
    ]
