# Generated by Django 2.2.5 on 2021-01-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210111_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domesticinvoice',
            name='vendor_code',
        ),
    ]
