# Generated by Django 2.2.5 on 2021-01-16 18:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210114_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualDomesticinvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, help_text='Name of the Part', max_length=100, null=True, verbose_name='Part Name')),
                ('invoiceNumber', models.CharField(max_length=40, verbose_name='Invoice Number')),
                ('invoiceDate', models.DateField(verbose_name='Invoice Date')),
                ('invoice_quantity', models.DecimalField(decimal_places=3, help_text='Invoice Quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice Quantity')),
                ('invoice_amount', models.DecimalField(decimal_places=3, help_text='Invoice Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice Amount')),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Invoice GST (%)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice GST Percentage')),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=3, help_text='Invoice GST Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice GST Amount')),
                ('total_amount', models.DecimalField(decimal_places=3, help_text='Invoice amount + GST Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Invoice Amount')),
                ('price_per_part', models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Price per Part', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price per Part')),
                ('remarks', models.CharField(blank=True, help_text='Invoice Remarks', max_length=200, null=True, verbose_name='Remarks')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Parts', verbose_name='Part Number')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.UnitOfMeasure', verbose_name='Unit of Measure')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Vendor', verbose_name='Vendor Name')),
            ],
            options={
                'db_table': 'IndividualDomesticinvoice',
                'ordering': ['updated'],
                'permissions': [('full_details_domesticinvoice', 'Can View Full Details Domesticinvoice')],
            },
        ),
    ]
