# Generated by Django 2.2.5 on 2021-01-17 20:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210117_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GST Amount'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='invoice_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice Quantity'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='part_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='price_per_part',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price per Part'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, help_text='Amount + GST Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount'),
        ),
    ]
