# Generated by Django 2.2.5 on 2021-01-17 20:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210118_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total Raw Material Cost of an Asset', max_digits=20, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='averageprice',
            name='average_price',
            field=models.DecimalField(decimal_places=2, help_text='Average Price of a part', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Average Price'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, help_text='Invoice amount + GST Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Invoice Amount'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='transport_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Transport Charges'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GST Amount'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='gst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='GST %'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='price_per_part',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price per Part'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount + GST Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='transport_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport Charges if any', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Transport Charges'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='transport_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport Charges if any', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Transport Charges'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='bank_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bank Charges if any', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bank Charges'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='bcd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basic Customs Duty Percentage', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='BCD Percentage'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='bcd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basic Customs Duty Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='BCD Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='clearance_charges_nontaxable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non Taxable Clearance Charges', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Clearance Charges Non Taxable'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='clearance_charges_taxable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxable Clearance Charges', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Clearance Charges Taxable'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='clearance_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Clearance GST Percentage', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Clearance GST %'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='clearance_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Clearance GST Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Clearance GST Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='customs_fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customs Fine Amount if any', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Customs Fine Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='customs_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customs GST Percentage', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Customs GST %'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='customs_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customs GST Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Customs GST Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='fright_charges_nontaxable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Non Taxable Freight Charges', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Freight Charges Non Taxable'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='fright_charges_taxable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxable Freight Charges', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Freight Charges Taxable'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='fright_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freight GST Percentage', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Freight GST %'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='fright_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Freight GST Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Freight GST Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='intrest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest Amount if any', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Interest Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='invoice_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice GST Percentage', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice GST %'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='invoice_gst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Invoice GST Amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice GST Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='invoice_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Invoice Quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice Quantity'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='local_transport_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Local Transport Fee', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Local Transport Fee'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='price_per_part',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Price per Part', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price per Part'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='total_clearance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Clearance Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Clearance Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='total_duty_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of the BCD amount + Customs GST Amount + Fine Amount + Intrest Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Duty Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='total_fright_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total Freight Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Freight Amount'),
        ),
        migrations.AlterField(
            model_name='overseasinvoice',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=2, help_text='Sum of the Invoice amount + Invoice GST Amount + Banck Charges', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Invoice Amount'),
        ),
    ]
