# Generated by Django 2.2.5 on 2021-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210122_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='unit_of_measure',
            field=models.CharField(max_length=20, verbose_name='Unit of Measure'),
        ),
    ]
