# Generated by Django 2.2.5 on 2021-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210122_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Vendor Name'),
        ),
    ]
