# Generated by Django 2.2.5 on 2021-01-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20210122_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Parts', verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.UnitOfMeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='individualdomesticinvoice',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Vendor', verbose_name='Vendor Name'),
        ),
    ]
