# Generated by Django 2.2.5 on 2021-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20210122_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='dimensions',
            field=models.CharField(blank=True, max_length=60, verbose_name='Part Dimensions'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='lead_time',
            field=models.PositiveIntegerField(verbose_name='Lead time (in Days)'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_class',
            field=models.CharField(blank=True, max_length=60, verbose_name='Part Class'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_description',
            field=models.CharField(max_length=500, verbose_name='Part Description'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_life',
            field=models.CharField(blank=True, max_length=120, verbose_name='Part Life'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='reorder_point',
            field=models.PositiveIntegerField(verbose_name='Reorder Point'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='safety_stock',
            field=models.PositiveIntegerField(verbose_name='Safety Stock'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='tech_spec',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tech Specifications'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='vendor_name',
            field=models.CharField(max_length=100, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='Weight'),
        ),
    ]
