# Generated by Django 2.2.5 on 2021-01-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210124_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='part_image',
        ),
    ]
