#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys
import time
import psycopg2

counter = 5

for i in range(0, counter):
    time.sleep(5)
    try:
        psycopg2.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        print("DB Connection OK.")
        sys.exit(0)

    except psycopg2.OperationalError:
        print("DB Connection Failied. Retrying...")
        pass

print("DB Connection Failied. Timeout after 5 retires..")
sys.exit(-1)
  
END
}


postgres_ready

# start cron
/usr/sbin/crond -f -l 8 &

exec "$@"
