# Generated by Django 2.2.5 on 2021-01-04 19:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210104_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inward',
            name='defected_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Defected Quantity Received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Defected Items Quantity'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='from_warehouse_name',
            field=models.ForeignKey(blank=True, help_text='Select Warehouse Name if Part is internal transferred', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_from_warehouse_name', to='inventory.Warehouse'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='invoice_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Invoice Quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Invoice Quantity'),
        ),
        migrations.AlterField(
            model_name='inward',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity Received', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Received Quantity'),
        ),
        migrations.AlterField(
            model_name='outward',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Quantity'),
        ),
    ]
