# Generated by Django 2.2.5 on 2021-01-11 11:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210109_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticinvoice',
            name='remarks',
            field=models.CharField(blank=True, help_text='Invoice Remarks', max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='domesticinvoice',
            name='total_invoice_amount',
            field=models.DecimalField(decimal_places=3, help_text='Invoice amount + GST Amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Invoice Amount'),
        ),
    ]
